export default {
  plugins: ["prettier-plugin-tailwindcss", "@trivago/prettier-plugin-sort-imports"],
  tailwindConfig: "./tailwind.config.ts",
  tabWidth: 2,
  printWidth: 120,
  useTabs: false,
  arrowParens: "always",
  bracketSpacing: true,
  bracketSameLine: true,
  jsxSingleQuote: false,
  quoteProps: "as-needed",
  semi: true,
  singleQuote: false,
  trailingComma: "es5",
  singleAttributePerLine: true,
  importOrder: ["^react", "^next", "<THIRD_PARTY_MODULES>", "^@/components", "^@/utils", "^[./]", "^[../]", "\\.css$"],
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
  importOrderCaseInsensitive: true,
};
